### ISSUE TITLE
Power BI Connection Timeout Issue, Win10

### ISSUE THREAD

**Issue by OksanaStrog** [ClickHouse/clickhouse-odbc#219]
Hello, 

Could you please help me to resolve the issue : "ODBC: ERROR [HY000] Timeout: connect timed out: [::1]:8443"?  I need to get data from the local host ClickHouse database and visualise them in Power BI. 

For that purpose I've installed first 64-bit, than 32-bit versions of driver, and in both cases the connection returns timeout error. When I tried to connect ClickHouse, I followed the next steps in Power BI: 

1. Get Data —> ODBC 
2. Then I chose from the list name ClickHouseDSN_localhost. 
3. After that I tried to fill in the Advanced Options: 

- in the Connection string (non-credential properties) I pasted: 
;Connect Timeout=600
- in the SQL query I put the next text: 
SELECT * 
FROM demo.table_name

4. In the next dialogue window in inserted user data: login and password in the dedicated fields and entered the dataset name. 
5. Finally, I got "Connection Timeout" error. 

I also tried to leave all the fields empty in the Advanced Options. That led to the same issue. 
As another option, I tried to paste the next text in the Connection string in the step 3: 

_https://username:password@indexesandparameters.mdb.yandexcloud.net:8443/query?database=demo&receive_timeout=6000&connect_timeout=600_
Eventually, it returned the same error. 

Could you please recommend what should I do to fix the issue? 
Thank you so much.

**Comment by traceon** [comment]
Do you have ClickHouse server running on `localhost` i.e. `[::1]:8443`? (assuming you don't since it's Windows 10)

> https://username:password@indexesandparameters.mdb.yandexcloud.net:8443/query?database=demo&receive_timeout=6000&connect_timeout=600

Is it a publicly available running ClickHouse instance?

**Comment by OksanaStrog** [comment]
@traceon thank you for the question. 
You're right, I don't have ClickHouse locally on my PC. I need to connect to the host which is available in our organisation. 

Before the attempt with the ODBC I had successfully queried against that database via Web link in Power BI. As the result, I got the CSV file.

**Comment by traceon** [comment]
It's hard for me to diagnose connection-related issues remotely, however, if you get `connect timed out` that at least indicates that the driver is recognized and loaded.

The `host:port` it is unable to connect to must match those specified in the DSN that you think you are using. The URL in that DSN must match the expected URL of the ClickHouse instance, which is (the URL) verified to work side-by-side on the same machine using some other tool (Web link in Power BI is OK).

Another thing that could prevent the driver from connecting to the remote ClickHouse instance using otherwise working URL is a possible SSL certificate check failure. To enable more tolerant behavior (at your own risk) try specifying `sslmode = allow` in the DSN.

**Comment by filimonov** [comment]
The url looks like Yandex Cloud managed ClickHouse. 
They use client certificates to connect to ClickHouse, you need to install that into your system.

Please consult Yandex Cloud support.
