### ISSUE TITLE
Can't build 1.1.3 on Ubuntu 18.04 with default settings

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/clickhouse-odbc#263]

**Comment by traceon** [comment]
As discussed offline, the problem was in CMake putting `libodbcint.so` in linker command line before any object file that requires it so linker ignored it.

Some weird behavior of version comparison triggered workarounds for older versions (using `target_link_options()` instead of unavailable `target_link_libraries()` for imported interface targets) that in their turn were incorrect.

Fixed by slightly bumping the minimum required version of CMake (from `3.12` to `3.13.5`) and using only `target_link_libraries()`.
