### ISSUE TITLE
UInt64 is not recognized to Tableau

### ISSUE THREAD

**Issue by dima-altinity** [ClickHouse/clickhouse-odbc#365]
Tableau generates error if you try to use open table with UInt64 type.

Error is: An error occurred while loading the data. Cannot interpret '18150585289071012696' as signed 64-bit integer: stoll argument out of range

Steps to reproduce:
Connect to ClickHouse Playground database from Tableau and try to open "hits_100m_obfuscated" table.

**Comment by nvm1** [comment]
@dima-altinity , I guess the problem is that Tableau does not support unsigned integers :( We encountered this problem as well and the only possible solution here is to cast to string columns which values might exceed int64 values.

https://help.tableau.com/current/api/hyper_api/en-us/reference/sql/datatype-numeric.html

**Comment by nvm1** [comment]
> @dima-altinity , I guess the problem is that Tableau does not support unsigned integers :( We encountered this problem as well and the only possible solution here is to cast to string columns which values might exceed int64 values.
> 
> https://help.tableau.com/current/api/hyper_api/en-us/reference/sql/datatype-numeric.html

Well, noticed that it's linked to #356 and I see that you will interpret those large values as string. That would be great. Thank you!

**Comment by traceon** [comment]
Yes, somehow Tableau was binding a **signed** 64-bit integer to columns that were reported as `SQL_BIGINT` with unsigned attribute on the column set to **true**. So the only workaround here, is just to report those columns as strings to Tableau.
